effort_joint_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - an_an_joint1
    - an_an_joint2
    - an_an_joint3
    - an_an_joint4
    - an_an_joint5
    - an_an_joint6
    - an_an_joint7
    - pan_pan_joint1
    - pan_pan_joint2
    - pan_pan_joint3
    - pan_pan_joint4
    - pan_pan_joint5
    - pan_pan_joint6
    - pan_pan_joint7
  constraints:
    goal_time: 0.5
    an_an_joint1:
      goal: 0.05
    an_an_joint2:
      goal: 0.05
    an_an_joint3:
      goal: 0.05
    an_an_joint4:
      goal: 0.05
    an_an_joint5:
      goal: 0.05
    an_an_joint6:
      goal: 0.05
    an_an_joint7:
      goal: 0.05
    pan_pan_joint1:
      goal: 0.05
    pan_pan_joint2:
      goal: 0.05
    pan_pan_joint3:
      goal: 0.05
    pan_pan_joint4:
      goal: 0.05
    pan_pan_joint5:
      goal: 0.05
    pan_pan_joint6:
      goal: 0.05
    pan_pan_joint7:
      goal: 0.05
  gains:
    pan_pan_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    pan_pan_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    pan_pan_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    pan_pan_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    pan_pan_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    pan_pan_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    pan_pan_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}
    an_an_joint1: {p: 600, d: 30, i: 0, i_clamp: 1}
    an_an_joint2: {p: 600, d: 30, i: 0, i_clamp: 1}
    an_an_joint3: {p: 600, d: 30, i: 0, i_clamp: 1}
    an_an_joint4: {p: 600, d: 30, i: 0, i_clamp: 1}
    an_an_joint5: {p: 250, d: 10, i: 0, i_clamp: 1}
    an_an_joint6: {p: 150, d: 10, i: 0, i_clamp: 1}
    an_an_joint7: {p: 50, d: 5, i: 0, i_clamp: 1}

pan_pan_state_controller:
  type: franka_control/FrankaStateController
  arm_id: pan_pan
  joint_names:
    - pan_pan_joint1
    - pan_pan_joint2
    - pan_pan_joint3
    - pan_pan_joint4
    - pan_pan_joint5
    - pan_pan_joint6
    - pan_pan_joint7
  publish_rate: 30  # [Hz]

an_an_state_controller:
  type: franka_control/FrankaStateController
  arm_id: an_an
  joint_names:
    - an_an_joint1
    - an_an_joint2
    - an_an_joint3
    - an_an_joint4
    - an_an_joint5
    - an_an_joint6
    - an_an_joint7
  publish_rate: 30  # [Hz]
