controller_list:
- name: combined_arms_controller 
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - an_an_joint1
    - an_an_joint2
    - an_an_joint3
    - an_an_joint4
    - an_an_joint5
    - an_an_joint6
    - an_an_joint7
    - pan_pan_joint1
    - pan_pan_joint2
    - pan_pan_joint3
    - pan_pan_joint4
    - pan_pan_joint5
    - pan_pan_joint6
    - pan_pan_joint7